Vagrant.configure("2") do |config|

  config.package.name = "archlinux"

  config.vm.box = "archlinux"
  config.vm.hostname = "arch"

  $script = "/bin/bash --login /vagrant/provisioners/install-packages.sh"

  config.vm.provision :shell, privileged: false, inline: $script

  config.vm.provider :virtualbox do |vb|
    
    vb.name = "arch"
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--usb", "on"]

  end

end
