# -*- mode: ruby -*-

PASSWORD = "foo"


Vagrant.configure("2") do |config|

  config.package.name = "archlinux"
  config.vm.box = "archlinux"
  config.vm.hostname = "arch"

  $install_packages = "/bin/bash --login /vagrant/provisioners/install-packages.sh"

  config.vm.provision :shell, privileged: false, inline: $install_packages

  config.vm.provider :virtualbox do |vb|
    
    vb.name = "arch"
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["usbfilter", 'add', '0', '--target', :id, '--name', 'Yubikey', '--vendorid', '0x1050', '--productid', '0x0407']
  end

end
