version: 2.1
jobs:
  build:
    docker:
      - image: base/archlinux
    steps:
      - run:
        name: Greeting
        command: echo Hello, world.
      - run:
        name: Print the Current Time
        command: date