version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: apt-get install -y vagrant
      - run: apt-get install -y packer
      - run: echo "A first hello"
