FROM archlinux/base

RUN pacman --noconfirm -Syy git \
                            ssh \
                            tar \
                            gzip \
                            ca-certificates
